from google.cloud import bigquery
import os

# ---------------------------
# GLOBAL CONFIGURATION
# ---------------------------
PROJECT_ID = os.environ["PROJECT_ID"]
DATASET_ID = os.environ["DATASET_ID"]
LOCATION = os.environ["LOCATION"]

# ---------------------------
# TABLE CONFIGURATIONS
# ---------------------------
TABLE_CONFIGS = [
    {
        "table_id": "visibility",
        "partition_column": "created_at",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,  # 7 days
        "schema": [
            bigquery.SchemaField("client_account_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("client_name", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("resource_name", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("resource_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("vpc_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("subnet_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("parent_resource_id", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("parent_resource_name", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("state", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("scan_time", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("created_at", "TIMESTAMP", mode="NULLABLE"),
            bigquery.SchemaField("year", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("month", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("day", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("hour", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("minute", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("data", "STRING", mode="NULLABLE"),
        ],
    },
    {
        "table_id": "os_linux_auditd",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("type", "STRING"),
            bigquery.SchemaField("serial_number", "STRING", description="Extracted serial number from msg field"),
            bigquery.SchemaField("syscall", "STRING"),
            bigquery.SchemaField("success", "STRING"),
            bigquery.SchemaField("args", "STRING", description="Combined arguments from a0, a1, a2, a3"),
            bigquery.SchemaField("pid", "STRING"),
            bigquery.SchemaField("ppid", "STRING"),
            bigquery.SchemaField("auid", "STRING"),
            bigquery.SchemaField("uid", "STRING"),
            bigquery.SchemaField("gid", "STRING"),
            bigquery.SchemaField("euid", "STRING"),
            bigquery.SchemaField("suid", "STRING"),
            bigquery.SchemaField("fsuid", "STRING"),
            bigquery.SchemaField("comm", "STRING"),
            bigquery.SchemaField("exe", "STRING"),
            bigquery.SchemaField("subj", "STRING"),
            bigquery.SchemaField("key", "STRING"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("event_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("event_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("event_time_timestamp_utc", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_linux_auth",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("message", "STRING"),
            bigquery.SchemaField("process", "STRING"),
            bigquery.SchemaField("hostname", "STRING"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("event_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("event_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("event_time_timestamp_utc", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_linux_cron",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("schedule", "STRING"),
            bigquery.SchemaField("command", "STRING"),
            bigquery.SchemaField("file_path", "STRING"),
            bigquery.SchemaField("user_name", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_linux_dirlist",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("file_name", "STRING"),
            bigquery.SchemaField("file_path", "STRING"),
            bigquery.SchemaField("md5_sum", "STRING"),
            bigquery.SchemaField("sha1_sum", "STRING"),
            bigquery.SchemaField("sha256_sum", "STRING"),
            bigquery.SchemaField("file_permission", "STRING"),
            bigquery.SchemaField("size", "INT64"),
            bigquery.SchemaField("creation_time", "TIMESTAMP"),
            bigquery.SchemaField("yara_results", "STRING", mode="REPEATED"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("owner", "STRING"),
            bigquery.SchemaField("group", "STRING"),
            bigquery.SchemaField("symbolic_link", "STRING"),
        ],
    },
    {
        "table_id": "os_linux_history",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("command", "STRING"),
            bigquery.SchemaField("file_path", "STRING"),
            bigquery.SchemaField("user_name", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_linux_hosts",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("ip_address", "STRING"),
            bigquery.SchemaField("hostnames", "STRING", mode="REPEATED"),
            bigquery.SchemaField("file_path", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_linux_services",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("creation_time", "TIMESTAMP"),
            bigquery.SchemaField("unit", "STRING"),
            bigquery.SchemaField("install", "STRING"),
            bigquery.SchemaField("service", "STRING"),
            bigquery.SchemaField("file_name", "STRING"),
            bigquery.SchemaField("file_path", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_linux_users_groups",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("group_name", "STRING"),
            bigquery.SchemaField("gid", "STRING"),
            bigquery.SchemaField("members", "STRING", mode="REPEATED"),
            bigquery.SchemaField("file_path", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("runas", "STRING", mode="REPEATED"),
            bigquery.SchemaField("commands", "STRING", mode="REPEATED"),
            bigquery.SchemaField("uid", "STRING"),
            bigquery.SchemaField("username", "STRING"),
            bigquery.SchemaField("description", "STRING"),
            bigquery.SchemaField("home_directory", "STRING"),
            bigquery.SchemaField("shell", "STRING"),
        ],
    },
    {
        "table_id": "os_windows_dirlist",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("file_name", "STRING"),
            bigquery.SchemaField("file_path", "STRING"),
            bigquery.SchemaField("md5_sum", "STRING"),
            bigquery.SchemaField("sha1_sum", "STRING"),
            bigquery.SchemaField("sha256_sum", "STRING"),
            bigquery.SchemaField("file_permission", "STRING"),
            bigquery.SchemaField("size", "INT64"),
            bigquery.SchemaField("creation_time", "TIMESTAMP"),
            bigquery.SchemaField("yara_results", "STRING", mode="REPEATED"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_windows_event_logs",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("file_name", "STRING"),
            bigquery.SchemaField("event_id", "STRING"),
            bigquery.SchemaField("windows_event_id", "STRING"),
            bigquery.SchemaField("event_description", "STRING"),
            bigquery.SchemaField(
                "data",
                "RECORD",
                fields=[
                    bigquery.SchemaField("Provider", "RECORD", fields=[
                        bigquery.SchemaField("Name", "STRING"),
                        bigquery.SchemaField("Guid", "STRING"),
                    ]),
                    bigquery.SchemaField("EventID", "STRING"),
                    bigquery.SchemaField("Version", "STRING"),
                    bigquery.SchemaField("Level", "STRING"),
                    bigquery.SchemaField("Task", "STRING"),
                    bigquery.SchemaField("Opcode", "STRING"),
                    bigquery.SchemaField("Keywords", "STRING"),
                    bigquery.SchemaField("TimeCreated", "RECORD", fields=[
                        bigquery.SchemaField("SystemTime", "TIMESTAMP"),
                    ]),
                    bigquery.SchemaField("EventRecordID", "STRING"),
                    bigquery.SchemaField("Correlation", "RECORD", fields=[
                        bigquery.SchemaField("ActivityID", "STRING"),
                        bigquery.SchemaField("RelatedActivityID", "STRING"),
                    ]),
                    bigquery.SchemaField("Execution", "RECORD", fields=[
                        bigquery.SchemaField("ProcessID", "STRING"),
                        bigquery.SchemaField("ThreadID", "STRING"),
                    ]),
                    bigquery.SchemaField("Channel", "STRING"),
                    bigquery.SchemaField("Computer", "STRING"),
                    bigquery.SchemaField("Security", "RECORD", fields=[
                        bigquery.SchemaField("UserID", "STRING"),
                    ]),
                    bigquery.SchemaField("Data", "STRING"),
                ],
            ),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("event_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("event_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("event_time_timestamp_utc", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_windows_file_system_autoruns",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("file_name", "STRING"),
            bigquery.SchemaField("file_path", "STRING"),
            bigquery.SchemaField("md5_sum", "STRING"),
            bigquery.SchemaField("sha1_sum", "STRING"),
            bigquery.SchemaField("sha256_sum", "STRING"),
            bigquery.SchemaField("file_owner", "STRING"),
            bigquery.SchemaField("creation_time", "TIMESTAMP"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_windows_hosts",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("ip_address", "STRING"),
            bigquery.SchemaField("hostnames", "STRING", mode="REPEATED"),
            bigquery.SchemaField("file_path", "STRING"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_windows_registry_autoruns",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("key_name", "STRING"),
            bigquery.SchemaField("key_fullpath", "STRING"),
            bigquery.SchemaField(
                "key_values",
                "RECORD",
                mode="REPEATED",
                fields=[
                    bigquery.SchemaField("value_name", "STRING"),
                    bigquery.SchemaField("value_type", "STRING"),
                    bigquery.SchemaField("value_data", "STRING"),
                ],
            ),
            bigquery.SchemaField("key_subkeys", "STRING", mode="REPEATED"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_windows_services",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("service_name", "STRING"),
            bigquery.SchemaField("display_name", "STRING"),
            bigquery.SchemaField("image_path", "STRING"),
            bigquery.SchemaField("start", "STRING"),
            bigquery.SchemaField("type", "STRING"),
            bigquery.SchemaField("description", "STRING"),
            bigquery.SchemaField("object_name", "STRING"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_windows_task_scheduler_autoruns",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("task_name", "STRING"),
            bigquery.SchemaField(
                "data",
                "RECORD",
                fields=[
                    bigquery.SchemaField("Task", "RECORD", fields=[
                        bigquery.SchemaField("version", "STRING"),
                    ]),
                    bigquery.SchemaField("Version", "STRING"),
                    bigquery.SchemaField("Description", "STRING"),
                    bigquery.SchemaField("URI", "STRING"),
                    bigquery.SchemaField("Principal", "RECORD", fields=[
                        bigquery.SchemaField("id", "STRING"),
                    ]),
                    bigquery.SchemaField("UserId", "STRING"),
                    bigquery.SchemaField("RunLevel", "STRING"),
                    bigquery.SchemaField("DisallowStartIfOnBatteries", "STRING"),
                    bigquery.SchemaField("StopIfGoingOnBatteries", "STRING"),
                    bigquery.SchemaField("MultipleInstancesPolicy", "STRING"),
                    bigquery.SchemaField("Priority", "STRING"),
                    bigquery.SchemaField("StartWhenAvailable", "STRING"),
                    bigquery.SchemaField("StopOnIdleEnd", "STRING"),
                    bigquery.SchemaField("RestartOnIdle", "STRING"),
                    bigquery.SchemaField("StartBoundary", "STRING"),
                    bigquery.SchemaField("DaysInterval", "STRING"),
                    bigquery.SchemaField("Actions", "RECORD", fields=[
                        bigquery.SchemaField("Context", "STRING"),
                        bigquery.SchemaField("Command", "STRING"),
                        bigquery.SchemaField("Arguments", "STRING"),
                    ]),
                ],
            ),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("command", "STRING"),
            bigquery.SchemaField("source_user_name", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_windows_users_groups",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("identity_type", "STRING"),
            bigquery.SchemaField("name", "STRING"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("last_modified_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("last_modified_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("last_modified_time_timestamp_utc", "TIMESTAMP"),
        ],
    },
    {
        "table_id": "os_windows_web_browsers",
        "partition_column": "scan_time_timestamp",
        "clustering_columns": [],
        "expiration_ms": 7 * 24 * 60 * 60 * 1000,
        "schema": [
            bigquery.SchemaField("client_instance_id", "STRING"),
            bigquery.SchemaField("client_account_id", "STRING"),
            bigquery.SchemaField("web_browser", "STRING"),
            bigquery.SchemaField("history_type", "STRING"),
            bigquery.SchemaField("id", "INT64"),
            bigquery.SchemaField("guid", "STRING"),
            bigquery.SchemaField("current_path", "STRING"),
            bigquery.SchemaField("target_path", "STRING"),
            bigquery.SchemaField("received_bytes", "INT64"),
            bigquery.SchemaField("total_bytes", "INT64"),
            bigquery.SchemaField("state", "INT64"),
            bigquery.SchemaField("danger_type", "INT64"),
            bigquery.SchemaField("interrupt_reason", "INT64"),
            bigquery.SchemaField("hash", "STRING"),
            bigquery.SchemaField("opened", "INT64"),
            bigquery.SchemaField("transient", "INT64"),
            bigquery.SchemaField("referrer", "STRING"),
            bigquery.SchemaField("site_url", "STRING"),
            bigquery.SchemaField("tab_url", "STRING"),
            bigquery.SchemaField("tab_referrer_url", "STRING"),
            bigquery.SchemaField("http_method", "STRING"),
            bigquery.SchemaField("by_ext_id", "STRING"),
            bigquery.SchemaField("by_ext_name", "STRING"),
            bigquery.SchemaField("by_web_app_id", "STRING"),
            bigquery.SchemaField("etag", "STRING"),
            bigquery.SchemaField("mime_type", "STRING"),
            bigquery.SchemaField("original_mime_type", "STRING"),
            bigquery.SchemaField("scan_time_timestamp", "TIMESTAMP"),
            bigquery.SchemaField("client_volume_id", "STRING"),
            bigquery.SchemaField("event_time_epoch_utc", "FLOAT64"),
            bigquery.SchemaField("event_time_timestamp_utc", "TIMESTAMP"),
            bigquery.SchemaField("event_time_timestamp", "TIMESTAMP"),
        ],
    },

]
